name: hitl_autofe
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - annotated-types==0.7.0
      - anyio==4.12.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - cloudpickle==3.1.2
      - distro==1.9.0
      - exceptiongroup==1.3.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - jiter==0.12.0
      - joblib==1.5.3
      - liac-arff==2.5.0
      - llvmlite==0.46.0
      - minio==7.2.20
      - numba==0.63.1
      - numpy==2.2.6
      - nvidia-nccl-cu12==2.28.9
      - openai==2.14.0
      - openml==0.15.1
      - packaging==25.0
      - pandas==2.3.3
      - pyarrow==22.0.0
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - shap==0.49.1
      - six==1.17.0
      - slicer==0.0.8
      - sniffio==1.3.1
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.2
      - xgboost==3.1.2
      - xmltodict==1.0.2
prefix: /home/xylar369/anaconda3/envs/hitl_autofe
